version: '2'

services:
  postgis:
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: cartologic
    ports:
      - "5432:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
  cartoview:
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    image: cartoview
    ports:
      - "8000:8000"
    depends_on:
      - postgis
    volumes:
      - "./cartoview_project:/cartoview_project"
  geoserver:
    image: geonode/geoserver:2.9.x-oauth2
    volumes:
      - "./geoserver/data:/geoserver_data/data"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
